# Config reference: https://rust-lang.github.io/rustfmt/
#
unstable_features = true

condense_wildcard_suffixes = true
fn_single_line = true
format_strings = true
imports_granularity = "Crate"
inline_attribute_width = 50
match_block_trailing_comma = true
max_width = 80
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
struct_field_align_threshold = 20
enum_discrim_align_threshold = 20                                              
use_field_init_shorthand = true
wrap_comments = true
trailing_comma = "Never"
chain_width = 60
